# Enable I2C
CONFIG_I2C=y

# Assertions for catching bugs during development
CONFIG_ASSERT=y

# Enable RTC subsystem
CONFIG_RTC=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
